# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='huowu',
            new_name='xiaoliang',
        ),
    ]
