# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test', '0003_delete_xiaoliang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(max_length=50)),
                ('Y', models.CharField(max_length=10)),
            ],
        ),
    ]
